-- AlterEnum: Add new lead status values
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'OTHER_CITY';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'NEGATIVE';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CONTRAINDICATION';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'NO_PICKUP';
