#!/bin/bash
echo "📦 Новый билд готов в dist/"
echo "📁 Bundle: index-CWjsixWN.js (новый!)"
echo ""
echo "🚀 РУЧНОЙ ДЕПЛОЙ:"
echo ""
echo "Вариант 1 - Через Vercel Dashboard:"
echo "1. Зайди Settings → Git"
echo "2. Проверь Root Directory = frontend"
echo "3. Reconnect репозиторий если нужно"
echo "4. Нажми Redeploy"
echo ""
echo "Вариант 2 - Drag & Drop:"
echo "1. Открой: https://vercel.com/new"
echo "2. Перетащи папку dist/ в окно"
echo "3. Vercel сам задеплоит"
echo ""
echo "✅ В dist/ новый код с исправлениями!"
